export enum OrderStatus{
    CANCELLED = "CANCELLED",
    DELIVERED = "DELIVERED",
    ORDERED = "ORDERED",
    RETURN_REQUESTED = "RETURN_REQUESTED",
    RETURNED = "RETURNED",
    SHIPPED = "SHIPPED",
    PROCESSING = "PROCESSING",
}